### ISSUE TITLE
Update for 1.2.0.17

### ISSUE THREAD

**Issue by git-iso** [Diverclaim/UnderrailMods#2]
Update seems to have broken mods.

**Comment by Diverclaim** [comment]
@git-iso 
Check releases, let me know if it works.

**Comment by git-iso** [comment]
Item weight mod seems to be broken, trader mods and speedup work fine.

**Comment by Diverclaim** [comment]
@git-iso 
Try hotfix.

**Comment by git-iso** [comment]
It works! Thanks for your help in spite of styg's autism.
