### ISSUE TITLE
1.2.0.18 update

### ISSUE THREAD

**Issue by tuasq** [Diverclaim/UnderrailMods#3]
It seems like hotfix just happened and game got updated, are we going to get mod update soon?

**Comment by Diverclaim** [comment]
@tuasq 
Well i'll try to look at it today, but if hotfix changes are not so important to you, you can try putting *.exe from 1.2.0.17 version, maybe it will work.

**Comment by tuasq** [comment]
Ok, i'll try that for now.

**Comment by KameBA** [comment]
Yup, it works. It shows save file is not compatible but works fine when I choose load awyway.

**Comment by tuasq** [comment]
1.2.0.20 came out, and i think that update just broke vendor.

other stuff works but vendor appear empty.

**Comment by Diverclaim** [comment]
@tuasq try latest release

**Comment by tuasq** [comment]
i just tested it on 1.2.0.20 gog build and it works, i'll close this one since it served its purpose
